version: "3.7"

services:
  nginx:
    image: jmarkin/full_nginx:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - TZ=${TZ:-Europe/Moscow}
